ejoffe/spr

- config/config.go
- config/config_test.go
- github/githubclient/client.go
- github/pullrequest.go
- spr/spr.go
* Parse custom GitHub hostnames from Git remote URLs;
* Allow setting GitHub hostname explicitly in the config;
* Connect to hosts other than `github.com` with `githubv4.NewEnterpriseClient`
* Updated unit tests.
Also tested with our GitHub enterprise server.
> Add support for GitHub Enterprise

- config/config.go
- github/githubclient/client.go
- github/pullrequest.go
- go.mod
- go.sum
- readme.md
- spr/spr.go
**Stack**:
- #155
- #156 ⮜
- #154
- #153
- #152
- #151
- #150
- #149
- #148
- #147
<pre>
Turns out "hub" is deprecated and GitHub wants you
to use this one instead: <a href="https://cli.github.com">https://cli.github.com</a>
From playing with it, it seems strictly superior to hub
since it does browser-based authentication and has a much
wider array of supported operations.
commit-id:48660ea6
</pre>
⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*
> Support the "gh" CLI tool in addition to "hub"

- github/githubclient/client.go
- github/githubclient/client_test.go
Previously, the commit description was dropped in after the stack list and was in a pre-formatted block, which removes any markdown formatting and other niceties of description commit bodies.
This instead pulls the commit body to the top, and adds a horizontal divider, after which the SPR stack and other trailer info is added. This keeps the PR description more in line with the commit message, while still including the Stack info.
---
This also adds unit tests for the description formatting. The first commit in this PR adds just the tests for the existing description formatting. The 2nd commit then updates the formatting output. Should make reviewing easier by reviewing each commit separately.
> Update PR description formatting.

- git/realgit/realcmd.go
If a user overrides `core.editor` in their `.gitconfig`, that setting
takes precedence over `$EDITOR`, which breaks the command. Instead,
use the `-c` flag, which has precedence over `.gitconfig`.
> Use `-c core.editor` git flag instead of `EDITOR` environment variable

- config/config.go
- github/githubclient/client.go
- readme.md
I prefer to use the GitHub UI to do a last check on the generated PRs
before sending them for review. This change adds a user config option
`createDraftPRs` that, when set to true, creates new PRs as drafts.
commit-id:d78551e5
> Add support for creating draft PRs.

- .spr.yml
- config/config.go
- config/config_test.go
- github/githubclient/client.go
- github/interface.go
- github/mockclient/mockclient.go
- readme.md
- spr/spr.go
- spr/spr_test.go
Update the `GitHubInterface.MergePullRequest` interface to take a `mergeMethod` argument from the repo configuration. This is a workaround for target branches that require signed commits as described in issue https://github.com/ejoffe/spr/issues/195.
I tested it manually also using `squash` and `merge` methods, and verified the error handling from the CLI.
`merge`: wade13/workflow-demo#27
`squash`: wade13/workflow-demo#25
> github: apply rebaseMerge config in MergePullRequest implementation

- github/pullrequest.go
Emojis messed up the string length calculation resulting in truncation of status line way shorter than the terminal width.
> Fix status length calc bug with new status emojis

- github/githubclient/client.go
- github/githubclient/client_test.go
As discussed in #200, at least Ubuntu does not support the current
left-arrow symbol "⮜". While not the best choice, "Leftwards Black
Arrow" is at least more available, it would seem.
> github: use a more common left-arrow for PR descriptions

- hook/install.go
In a git worktree .git is actually a file that points to the location
of the woktree .git directory.  To get the right location for commit
hook installation the --git-common-dir flag needs to be used instead.
> Fix hook installation when in a git worktree

- git/mockgit/mockgit.go
- github/githubclient/client.go
- spr/spr.go
The commit log and git branch parsing was not working when my commands
were getting colorized.  Explicitly pass --no-color to these two
commands to turn off colors.
> Turn off colors when reading branch and log

- github/githubclient/client.go
Once upon a time, the commit message body was included in the PR description inside a pre-formatted code block. This did not allow for Markdown formatting, so it was removed in 1606b8ff251c293136419852f4cb9995734dcadc, but the code to wrap links in `<a>` tags and extract issue references was not removed. This code is now not needed and messes up other formatting.
Fixes https://github.com/ejoffe/spr/issues/237
> Remove code left over from pre-formatting message

- spr/spr.go
- spr/spr_test.go
The [] misled me into thinking there was a default.
> amend: replace [] with ()

- hook/install.go
Fix critical bug introduced with #206 that completely broke the spr experience starting from 0.8.3.
This fix should retain the intended feature introduced with #206, while falling back to the previously working root directory when `.git` directory is not found.
``` bash
$ git amend
> git rev-parse --show-toplevel
> git log --no-color origin/master..HEAD
> git rev-parse --git-common-dir
2022/06/05 14:15:00 chdir .git: no such file or directory
```
``` bash
$ git spr u
> git rev-parse --show-toplevel
> git fetch
> git rebase origin/master --autostash
> github fetch pull requests
> git branch --no-color
> git log --no-color origin/master..HEAD
> git rev-parse --git-common-dir
> git rebase origin/master -i --autosquash --autostash
> git log --no-color origin/master..HEAD
panic: unable to …
```
> Fix critical bug introduced with #206

- readme.md
Unfortunately https://github.com/getcord/spr is installed when running `brew install spr`. I was only able to get the ejoffe version with the proposed change.
> Disambiguate from getcord/spr which brew installs

- readme.md
As a non-root user, the existing command to update the apt sources list fails due to a lack of permissions. The updated command uses `sudo` to gain the permissions needed and `tee` to write the changes to the file.
> Update Apt install to work with file permissions

- config/config.go
- config/config_test.go
- github/githubclient/client.go
- github/githubclient/client_test.go
- github/githubclient/gen/genclient/client.go
- github/githubclient/gen/genclient/operations.go
- github/githubclient/queries.graphql
- github/pullrequest.go
- readme.md
This change adds support for pull request templates and closes #266. It adds three new repo config settings:
* `prTemplatePath` - path to PR template (e.g. .github/PULL_REQUEST_TEMPLATE/pull_request_template.md)
* `prTemplateInsertStart` - text to search for in PR template that determines body insert start location
* `prTemplateInsertEnd` - text to search for in PR template that determines body insert end location
* Repo settings
```
prTemplatePath: .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
prTemplateInsertStart: "# Description"
prTemplateInsertEnd: "# Checklist"
```
* PR template contents for `.github/PULL_REQUEST_TEMPLATE/pull_request_template.md`
```
<add related issues here>
<add description here>
[ ] A checklist item
```
* Commits
* add file 1
* add file 2
* Resulting PR …
> Add support for PR templates

- git/mockgit/mockgit.go
- spr/spr.go
parseLocalCommitStack assumes the commit log string conforms to --pretty=/--format=medium. If the user has a custom setting for format.pretty in .gitconfig (for example: oneline) , this assumption can break and spr reports:
"pull request stack is empty".
This commit changes the git log command to always specify --format=medium to avoid this issue.
> Tolerate custom format.pretty settings in user .gitconfig

- github/githubclient/client.go
- github/interface.go
- github/mockclient/mockclient.go
- spr/spr.go
- spr/spr_test.go
Fixes #277
I'm not sure how useful this is. It seems to work but I have next to zero experience w/golang. I also wasn't sure if there was a good facility in place to test this... I looked at the existing `TestSPRReorderCommit` but it seems the mock github client isn't really set up to verify on the passed in `github.GItHubInfo`
> Update PR descriptions after commit reordering

- Makefile
When running `make` I see this deprecation warning:
```
Flag --rm-dist has been deprecated, please use --clean instead
```
I run this version of `goreleaser`:
```
$ goreleaser --version
____       ____      _
/ ___| ___ |  _ \ ___| | ___  __ _ ___  ___ _ __
| |  _ / _ \| |_) / _ \ |/ _ \/ _` / __|/ _ \ '__|
| |_| | (_) |  _ <  __/ |  __/ (_| \__ \  __/ |
\____|\___/|_| \_\___|_|\___|\__,_|___/\___|_|
goreleaser: Deliver Go Binaries as fast and easily as possible
https://goreleaser.com
GitVersion:    1.19.1
GitCommit:     6b46a1a6aa51e45bd281d55b6e5a2315ee82f643
GitTreeState:  false
BuildDate:     2023-06-29T12:55:30Z
BuiltBy:       goreleaser
GoVersion:     go1.20.5
Compiler:      gc
ModuleSum:     h1:MVAFo62jkj6/JflxruefIwfFTqNTeNtkT12Hab1o2Lk=
Platform:      linux/amd64
```
> Address deprecation warning on goreleaser's --rm-dist

- .goreleaser.yml
The `archives.replacement` structure in the `.goreleaser.yml` was
deprecated and recently removed.
This change addresses this problem by using the proposed solution
from https://goreleaser.com/deprecations/#archivesreplacements with a
slight modification. Instead of title-cased replacements of the
operating system we want it to be all lowercase because that is how the
old replacement items looked like:
```yaml
archives:
- name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
replacements:
darwin: macos
linux: linux
windows: windows
386: i386
amd64: x86_64      
```
Hence the new `name_template` uses as lower-cased operating system name
(`{{- tolower .Os }}`) and a special handling for turning `darwin` into
`macos` as well as the architecture handling. …
> Address `archives.replacements` being removed from goreleaser

- spr/spr.go
Fixes the panic below:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x1049bfa50]
goroutine 52 [running]:
github.com/ejoffe/spr/github/githubclient.formatStackMarkdown({{0x140001c636d, 0x8}, {0x140001c61d0, 0x28}, {0x140001c6252, 0x23}, {0x140001e4001, 0xce}, 0x0}, {0x14000281e40, ...})
/Users/USER/go/src/github.com/ejoffe/spr/github/githubclient/client.go:399 +0x60
github.com/ejoffe/spr/github/githubclient.formatBody({{0x140001c636d, 0x8}, {0x140001c61d0, 0x28}, {0x140001c6252, 0x23}, {0x140001e4001, 0xce}, 0x0}, {0x14000281e40?, ...})
/Users/USER/go/src/github.com/ejoffe/spr/github/githubclient/client.go:424 +0xf0
github.com/ejoffe/spr/github/githubclient.(*client).UpdatePullRequest(0x140000aaa80, …
```
> fix: WIP commit panic in formatStackMarkdown

- .github/workflows/ci.yml
This adds a check to the CI workflow file to check for the sanity of the `.goreleaser.yml` file by running `goreleaser check`.
> Check goreleaser config in CI github workflow

- .goreleaser.yml
For some reason the `make` produced these archives:
```
• archives
• creating                                       archive=dist/spr_linux_x86_64 .tar.gz
• creating                                       archive=dist/spr_linux_arm64 .tar.gz
• creating                                       archive=dist/spr_windows_x86_64 .zip
• creating                                       archive=dist/spr_windows_arm64 .zip
• creating                                       archive=dist/spr_darwin_arm64 .tar.gz
• creating                                       archive=dist/spr_linux_i386 .tar.gz
• creating                                       archive=dist/spr_windows_i386 .zip
• creating                                       archive=dist/spr_darwin_x86_64 .tar.gz
```
Notice the space at the end. I guess it …
> Get rid of space at the end of archive name

- readme.md
Since #329 the `githubBranch` config option defaults to `main` instead of `master`. Update the readme to reflect this.
> Readme: githubBranch defaults to `main`

- github/githubclient/client.go
- github/githubclient/client_test.go
- github/githubclient/fezzik.yaml
- github/githubclient/fezzik_types/fezzik_types.go
- github/githubclient/gen/genclient/client.go
- github/githubclient/gen/genclient/inputs.go
- github/githubclient/gen/genclient/operations.go
- github/githubclient/queries.graphql
- go.mod
- go.sum
> Remove merge queue from query is feature is disabled

- config/config.go
- config/config_test.go
- github/githubclient/client.go
- github/githubclient/client_test.go
- readme.md
This PR adds a new repository config field that toggles displaying each PR's title in the PR body's stack description like so:
```
**Stack**:
- Title B #2 ⬅
- Title A #1
```
This is helpful for github enterprise instances that are not on the latest version where PR titles automatically populate alongside PR numbers.
The field is named `showPrTitlesInStack` and defaults to false.
I've added respective tests to maintain coverage with the added functionality in `github/githubclient/client.go` and have built and installed this binary locally to dogfood the new behavior.
> adds option to show pr titles in stack description

- config/config.go
- readme.md
- spr/spr.go
Atomically pushing all stacked branches at once can fail in larger and slower monorepos with pre-commit hook timeouts e.g.
```
% git spr update --detail
> git rev-parse --show-toplevel
> git fetch
> git rebase origin/master --autostash
> github fetch pull requests
> git log --format=medium --no-color origin/master..HEAD
> git branch --no-color
> git log --format=medium --no-color origin/master..HEAD
> git status --porcelain --untracked-files=no
> git push --force --atomic origin eddc899e328aa4b7819dd62f15dfdf5cbb489efb:refs/heads/spr/master/895c5bb2 cc639c1396bc68569e7f7887d2e60c167a543b19:refs/heads/spr/master/2a17fcc7 8bc3daa4d188043c2f226ac4c58a0688266aa2a0:refs/heads/spr/master/128d0ed9 cd1ae69fcc4c110a246036d27624594f57295a1a:refs/heads/spr/master/5a24cfff …
```
> Add `BranchPushIndividually` repo config

- cmd/spr/main.go
- config/config_parser/config_parser.go
- github/githubclient/star.go
Fixes #332
commit-id:a7c1a3c3
---
**Stack**:
- #380 ⬅
- #379
- #378
⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*
> Check for backslashes in remote branch name

- github/githubclient/client.go
As shared [in this comment](https://github.com/ejoffe/spr/issues/335#issuecomment-1968400630), gh cli has changed the default behavior of how github auth tokens are saved. This change makes spr no longer able to read github auth tokens and has caused myself and others confusion when instructions say to run `gh auth login` but still see spr not be able to find the token. 
This change updates the instructions to avoid this confusion. I do understand that suggesting to users to use insecure storage may not be ideal and a different solution may be preferred. Whatever solution it is, I believe it's better then today where users of spr receive these help docs, try them, and do not see success.
> update gh login instructions after gh CLI storage update

- readme.md
This PR removes `>`s from the install instructions command to make them copy/paste-able.
I didn't remove them in the example under that since those are not really meant to be used anyway but I can change that if you want everything to be aligned.
> remove `>` from the installation instructions

- config/config_parser/config_parser_test.go
- config/config_parser/remote_source.go
Fixes organization names with dashes not being properly detected by `getRepoDetailsFromRemote`. I've also added a few more test cases just to be sure.
> Fix getRepoDetailsFromRemote failing to detect repo owners that include dashes

- git/realgit/realcmd.go
This change disables (1) `commit.verbose` and (2) `rebase.abbreviateCommands` by default.
(1) Fixes https://github.com/ejoffe/spr/issues/316, but should be verified by @felixge
(2) Fixes https://github.com/ejoffe/spr/issues/409 for me.
> Disable git verbose commits and abbreviated rebase commands by default

- git/realgit/realcmd.go
> GITHUB-407: Gracefully handle Cygwin paths on Windows when determining root directory

- github/githubclient/client.go
- github/githubclient/client_test.go
The Github GraphQL response returns null for the StatusCheckRollup object if there are no status checks at all. In that case, this should be a pass.
From my understanding, spr gets the state of the PullRequest with a graphql query like the following:
```sh
gh api graphql -f query='
query PullRequest($repo_owner: String!, $repo_name: String!, $pr_number: Int!) {
viewer {
login
}
repository(owner: $repo_owner, name: $repo_name) {
pullRequest(number: $pr_number) {
id
number
title
body
baseRefName
headRefName
mergeable
reviewDecision
repository {
id
}
commits(first: 100) {
nodes {
commit {
oid
messageHeadline
messageBody
statusCheckRollup {
state
}
}
}
}
}
}
}' -f repo_owner='myrepo' -f repo_name='myrepo' -f pr_number=123
```
On the repository I am working on, this would give a response with …
> Fix status check not working for PRs without any status checks

- .github/workflows/ci.yml
- .goreleaser.yml
- Makefile
Fix #427
> --skip
>
>     since 2023-09-14 (v1.21), removed 2024-05-26 (v2.0)
>
> The following goreleaser release flags were deprecated:
>
>     --skip-announce
>     --skip-before
>     --skip-docker
>     --skip-ko
>     --skip-publish
>     --skip-sbom
>     --skip-sign
>     --skip-validate
See https://goreleaser.com/deprecations/#-skip
This also fixes a problem with the version of the `.goreleaser.yml`
which now has to be `version: 2`.
In order for the github workflow to not error with this message:
```console
$ goreleaser check
• by using this software you agree with its EULA, available at https://goreleaser.com/eula
• running goreleaser v2.7.0
• checking                                 path=.goreleaser.yml
• DEPRECATED:  snapshot.name_template  should not be used anymore, check …
```
> Fix goreleaser: Upgrade to v2 format and command line flag migration

- go.mod
- go.sum
This change addresses this issue:
```
go: downloading nhooyr.io/websocket v1.8.7
go: github.com/hasura/go-graphql-client@v0.9.3 requires
nhooyr.io/websocket@v1.8.7: reading nhooyr.io/websocket/go.mod at revision v1.8.7: unknown revision v1.8.7
```
> Address issue with go tidy and nhooyr.io/websocket

- cmd/spr/main.go
Do not run `UpdatePullRequests` when running the `merge` subcommand.
Suppose we have local commits: `c1`.
We do a git spr update and a PR is created for `c1`.
We then create local commits `c2` & `c3`.
If we run `git spr merge` then the following happens.
1. `c1` got merged
2. PRs are created for `c2` and `c3`
The creation of PRs for `c2` and `c3` is both unexpected and undocumented.
The use of `git spr merge` only claims to "merge all the pull requests that are
mergeable in one shot".
If you want to only merge some of the PRs then `git spr merge -c` is still available. If you want to create PRs for `c2` and `c3` then `git spr update` can still be used.
Note: This change was inspired by de380f0d2e505b43569fe2b3df0a05df4c3c0cf0.
> Don't update stack for `merge` (ever)

- config/config_parser/config_parser_test.go
- git/mockgit/mockgit.go
- github/mockclient/mockclient.go
- spr/spr_test.go
The unit tests didn't rigorously test expectations. This led to tests which were broken but passed anyway. For example for the git Mocks you could add expectations for X, Y, and Z and if only X and Y were called the tests would still pass. For the github mocks the same issue existed but also they would pass if X and Y expectations were set but X and Y were called multiple times. This change fixes both of these issues and fixes the unit tests so they are no longer broken.
> More rigorous test framework and fix tests

- spr/spr.go
This fixes https://github.com/ejoffe/spr/issues/420 
`sortPullRequestsByLocalCommitOrder` assumes that all commits in the stack will have a corresponding PR, which is not true.
Now I just need to figure out how to add a test for this ;)
> Fix segfault when running update with --count=1 on a stack with more than one commit

- git/realgit/realcmd.go
I use https://github.com/MitMaro/git-interactive-rebase-tool and it requires this change to be compatible with `spr`.
> feat(editor): support usage of alternative `sequence.editor`

- Makefile
`make bin` only builds native executables now.
I believe this is what the user would expect when they compile spr from source, and run `make bin` as instructed in readme.md.
> build: build only native executables by default
