ejoffe/spr

spr/spr.go

Fix handling SSH Agent keys

---

spr/config.go
spr/config_test.go

Fix repo name regex

---

.spr.yml
cmd/amend/main.go
cmd/spr/main.go
config/config.go
git/interface.go
git/mockgit/mockgit.go
git/realgit/realcmd.go
github/githubclient/client.go
github/interface.go
github/mockclient/mockclient.go
readme.md
spr/spr.go
spr/spr_test.go

Config file update

---

.spr.yml
cmd/spr/main.go
config/config.go
config/config_test.go

Handle dash in repository name

---

git/commit.go
git/mockgit/mockgit.go
git/realgit/realcmd.go
github/githubclient/client.go
github/mockclient/mockclient.go
github/pullrequest.go
hook/commithook.go
spr/spr.go
terminal/terminal_other.go

Fix some go lints

---

cmd/amend/main.go
readme.md

Amend logging fix

---

cmd/amend/main.go
github/githubclient/star.go
spr/spr_test.go

Fix git amend null config

---

docs/index.md

github pages update

---

github/githubclient/star.go
readme.md

resize screencast

---

.goreleaser.yml
Makefile
cmd/reword/main.go
git/interface.go
git/mockgit/mockgit.go
git/realgit/realcmd.go
github/githubclient/client.go
hook/install.go
readme.md
spr/spr.go
spr/spr_test.go

Auto install commit hook

---

.goreleaser.yml
Makefile

makefile : v0.7.3

---

cmd/spr/main.go
git/mockgit/mockgit.go
readme.md
spr/spr.go

Push refs instead of creating local branches

---

github/githubclient/client.go

Older versions of git don't support --show-current flag.
commit-id:e54c8b99

Use regular 'git branch' call instead of using --show-current

---

config/config.go
readme.md
spr/spr.go
spr/spr_test.go

Repo config for github remote and branch name

---

.spr.yml
cmd/amend/main.go

fixes: #101
commit-id:e0317625

Pass valid config to git amend

---

.github/workflows/cd.yml
.goreleaser.yml

CD is invoked by creating & pushing a new tag to origin.
Make sure to add the following secrets:
- FURY_TOKEN (Should be a push-only token)
- FURY_ORG (organization of gemfury)

Push packages to repo & Continuous Delivery

---

.github/workflows/cd.yml

cd action: rename GITHUB_TOKEN -> REPO_TOKEN

---

.goreleaser.yml
.spr.yml

spr config : add githubHost field

---

readme.md

readme : update installation section

---

.github/workflows/ci.yml
cmd/amend/main.go
cmd/spr/main.go
config/config_test.go
git/mockgit/mockgit.go
github/mockclient/mockclient.go
github/pullrequest_test.go
spr/spr.go
spr/spr_test.go

don't panic on git rebase error

---

config/config.go
config/config_test.go
git/mockgit/mockgit.go
github/githubclient/client.go
github/githubclient/client_test.go
readme.md
spr/spr.go

Add warning when running spr on remote pr branches

---

github/githubclient/client.go
go.mod

Support ~/.config/hub to acquire token

---

github/githubclient/client.go

Reference: #177
commit-id:d15eee74

Support dots in branch name

---

github/githubclient/client.go

Add `ref` as reference keyword

---

config/config.go
config/config_test.go
github/pullrequest.go
github/pullrequest_test.go
readme.md
spr/spr.go

Use emojis for "spr status" output

Use emojis for "spr status" output 

---

Makefile

this is now done via github action

delete make release from Makefile

---

spr/spr.go
spr/spr_test.go

As described in #199, we were calling GetAssignableUsers (a graphql
API query) for each new PR created. This is a property of the
repository, though, and we don't expect it to be changing while we're
pushing a single stack.
Stash the slice of RepoAssignee the first time it's needed and
continue to use it for the rest of the calls. Added a test case to
verify the behaviour.
**Issue references**: 
- #199

avoid multiple "GetAssignableUsers" calls when pushing a new stack

---

cmd/amend/main.go
git/mockgit/mockgit.go
spr/spr.go

fixes #222
**Issue references**: 
- fixes #222---
**Stack**:
- #229
- #228 ⬅
⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

Fix git amend to use configured upstream

---

.gitignore
github/githubclient/client.go
readme.md

Set Title and Body to nil when setting is true
Test on my repository with both value, it works as expected.
fixes #261

Fix `PreserveTitleAndBody` bug

---

readme.md

readme update : from source using goreleaser

---

cmd/reword/main.go

Tested that it works for the regular case.
Hopefully works for the missing newline case, I can't reproduce it in my env.

Fix missing newline before commit-id in some cases

---

readme.md

Improvements made:
- Replaced bolded **git spr** commands with `git spr` inline blocks
- Minor grammar improvements

Improve readability of readme.md

---

github/interface.go
spr/spr.go

fix spr check skip case

---

github/githubclient/client.go

Fix null ptr dereference in github user name

---

.spr.yml

config : remove old field

---

config/config_parser/config_parser.go

remove writing/updating of config files

---

config/config.go
config/config_parser/config_parser.go
config/config_parser/remote_branch.go
config/config_test.go
git/helpers.go
github/githubclient/client.go
readme.md
spr/spr.go
spr/spr_test.go

Fix remote origin branch config

---

readme.md

As discussed [here](https://github.com/ejoffe/spr/issues/377), a simple instruction on how to start a new stack.

include steps to create a new stack in readme

---

.github/workflows/ci.yml
LICENSE

add manual workflow dispatch action trigger

---

.github/workflows/ci.yml

github actions ci : add push trigger

---

.github/workflows/cd.yml

update cd github action : fix goreleaser version

---

spr/spr_test.go

Ensures that all expectations are met at key points in the unit tests.
Brings this test in line with other tests in the same file.

Improve TestSPRBasicFlowDeleteBranch test
